server:
  port: 8080
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        namespace: nvocc-cloud-example
        server-addr: 10.10.9.12:8848
    loadbalancer:
      ribbon:
        enabled: false